### ISSUE TITLE
Failed to load and run script

### ISSUE THREAD

**Issue by axcore** [ShadMOrdre/lib_materials#6]
Minetest 5.0.1, new world, the only mod enabled is lib_materials. The previous version of lib_materials works just fine (i just tested it).

When I start the world, using the new version of lib_materials, I see this error:

![error1](https://user-images.githubusercontent.com/37951926/64097145-57301e00-cd5b-11e9-8998-c1c3b5002d41.png)
![error2](https://user-images.githubusercontent.com/37951926/64097148-58614b00-cd5b-11e9-8135-cf4de6420b48.png)

**Comment by nyje** [comment]
Seconded, I too get the same error under latest stable MT & MTG:

`2019-09-02 12:16:36: ERROR[Main]: ModError: Failed to load and run script from /home/www-data/LIVE_SERVERS/T4/bin/../worlds/T4/worldmods/lib_materials/init.lua:
2019-09-02 12:16:36: ERROR[Main]: ...rlds/T4/worldmods/lib_materials/lib_materials_nodeio.lua:292: Attempt to override non-existent item default:chest
2019-09-02 12:16:36: ERROR[Main]: stack traceback:
2019-09-02 12:16:36: ERROR[Main]: 	[C]: in function 'error'
2019-09-02 12:16:36: ERROR[Main]: 	...ww-data/LIVE_SERVERS/T4/bin/../builtin/game/register.lua:388: in function 'override_item'
2019-09-02 12:16:36: ERROR[Main]: 	...rlds/T4/worldmods/lib_materials/lib_materials_nodeio.lua:292: in function 'init_main_inventory'
2019-09-02 12:16:36: ERROR[Main]: 	...worldmods/lib_materials/lib_materials_nodeio_support.lua:7: in main chunk
2019-09-02 12:16:36: ERROR[Main]: 	[C]: in function 'dofile'
2019-09-02 12:16:36: ERROR[Main]: 	...rlds/T4/worldmods/lib_materials/lib_materials_nodeio.lua:297: in main chunk
2019-09-02 12:16:36: ERROR[Main]: 	[C]: in function 'dofile'
2019-09-02 12:16:36: ERROR[Main]: 	...ERS/T4/bin/../worlds/T4/worldmods/lib_materials/init.lua:96: in main chunk`

**Comment by ShadMOrdre** [comment]
My apologies.

As I continue to work towards a larger goal, I removed the soft dependency on the default mod from MTG.  I'm dissecting the default mod, and so removed the soft dependency as a means to find those dependencies.  This one slipped right past me.

If you redownload the mod, this error should go away, since lib_materials is looking for "default:chest".  With the soft dependency on default re-added, lib_mat can now 'see' default.

Thanks for reporting. Please let me know if you experience any other issues.

**Comment by axcore** [comment]
I can now start a MT game, but with hundreds of red-text errors. Sorry, I don't know where the debug file (if any) is written, so I only have screenshots:

(This is a new MT game. The only mods enabled are lib_materials and lib_ecology)

![libmerror1](https://user-images.githubusercontent.com/37951926/64170725-b6b82780-ce48-11e9-9bb7-4a4e1bc8b26e.png)
![libmerror2](https://user-images.githubusercontent.com/37951926/64170727-b881eb00-ce48-11e9-9c4f-10e8d23584e4.png)

**Comment by ShadMOrdre** [comment]
axcore,

thanks for the feedback.  i've just pushed a commit that comments out the call to the lakes code.  can you verify if log clears up?

on windows,  debug.txt file is in the minetest folder, where ever you have that installed.  You can look at where the shortcut points, to find where your minetest is installed on your computer.

on linux, it is in ./minetest, a hidden folder in your home folder.

On android, i have no clue where the debug file is, but the screenshots are good.  Thanks again for helping with testing and debugging.

Shad

**Comment by axcore** [comment]
I'm sorry to say, that I am still getting thousands of errors. 

I emptied my ./minetest folder. Then I opened Minetest, which creates a new ./minetest folder. Then I downloaded new copies of lib_materials and lib_ecology. Then I created a game, with only those mods.  

[debug.txt](https://github.com/ShadMOrdre/lib_materials/files/3580754/debug.txt)

**Comment by ShadMOrdre** [comment]
So I've disabled the lakes code and some other code that may have been contributing to the mess, and my own debug file cleared right up.

I've also corrected some textures and other fixes.  Please let me know how this version works for you and any other issues you experience.

Again, thanks for the testing and feedback

**Comment by axcore** [comment]
Nope. I downloaded lib_materials and lib_ecology again, used another new game with only those mods enabled, and I'm still getting continuous errors.

[debug.txt](https://github.com/ShadMOrdre/lib_materials/files/3586352/debug.txt)

**Comment by ShadMOrdre** [comment]
Again, sorry for the errors.  I've tracked the issues to some bad decorations coming from lib_ecology.  Schematics that were no longer valid, or referenced the wrong nodes.  Most were actually water decorations.  I hope this has now cleared up.

I just posted a new update today.  Please, keep the feedback coming.  I appreciate your testing.  I quit using MTG and the default mod as a base.  As such, there are a number of things broken in a number of mods, but doing so greatly assisted in getting these two mods free of dependencies.  It also means that errors occur on my dev machine that require time and effort to track down.  It's worth it though.  I get to learn more about the code each time.

Shad

**Comment by axcore** [comment]
I am not seeing any more errors, but a default game is now exactly the same as a game with lib_materials and lib_ecology.

The screenshots show a new v7 world, one with lib_materials/lib_ecology enabled, one without. There are no other mods enabled. (I have tested several different worlds, same results.)

![mtgamemod](https://user-images.githubusercontent.com/37951926/65492159-5a28b500-dea8-11e9-8c75-be7434327e14.png)
![mtgamenomod](https://user-images.githubusercontent.com/37951926/65492165-5c8b0f00-dea8-11e9-8fdc-83bb52ae0563.png)
